spring.application.name=portfolio

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/portfolio?useSSL=false&serverTimezone=Asia/Tokyo&collation=utf8mb4_bin}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Ls-88888888}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Initialize data
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
jwt.secret=${JWT_SECRET:your-super-strong-secret-key-that-is-at-least-256-bits-long}
jwt.expiration=${JWT_EXPIRATION:60000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:86400000}

# Logging Configuration
logging.level.root=INFO
spring.output.ansi.enabled=always
